# Generated by Django 5.0 on 2026-06-18 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('devise', models.CharField(default='CDF', max_length=10)),
                ('methode', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('carte', 'Carte bancaire'), ('virement', 'Virement bancaire'), ('especes', 'Espèces à la livraison')], max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('rejete', 'Rejeté'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20)),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('reference_externe', models.CharField(blank=True, max_length=100)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='commandes.commande')),
            ],
        ),
    ]
