# Generated by Django 5.0 on 2026-06-18 13:16

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('agriculteur', 'Agriculteur'), ('acheteur', 'Acheteur'), ('transporteur', 'Transporteur'), ('admin', 'Administrateur')], max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('banni', 'Banni')], default='actif', max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProfilAcheteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_livraison', models.CharField(blank=True, max_length=300)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('type_acheteur', models.CharField(choices=[('particulier', 'Particulier'), ('revendeur', 'Revendeur'), ('restaurant', 'Restaurant'), ('supermarche', 'Supermarché')], default='particulier', max_length=20)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_acheteur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilAgriculteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exploitation', models.CharField(max_length=200)),
                ('localisation', models.CharField(max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('superficie', models.FloatField(blank=True, null=True)),
                ('types_production', models.TextField(blank=True)),
                ('note_moyenne', models.FloatField(default=0.0)),
                ('est_verifie', models.BooleanField(default=False)),
                ('revenus_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bio', models.TextField(blank=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_agriculteur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilTransporteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude_actuelle', models.FloatField(blank=True, null=True)),
                ('longitude_actuelle', models.FloatField(blank=True, null=True)),
                ('zone_couverture', models.TextField(blank=True)),
                ('disponible', models.BooleanField(default=True)),
                ('note_moyenne', models.FloatField(default=0.0)),
                ('revenus_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('est_verifie', models.BooleanField(default=False)),
                ('numero_permis', models.CharField(blank=True, max_length=50)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_transporteur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_vehicule', models.CharField(choices=[('camion', 'Camion'), ('moto', 'Moto'), ('voiture', 'Voiture'), ('tracteur', 'Tracteur'), ('camionnette', 'Camionnette')], max_length=20)),
                ('immatriculation', models.CharField(max_length=30, unique=True)),
                ('capacite_kg', models.FloatField()),
                ('est_refrigere', models.BooleanField(default=False)),
                ('annee', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehicules/')),
                ('est_actif', models.BooleanField(default=True)),
                ('transporteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='accounts.profiltransporteur')),
            ],
        ),
    ]
