# Generated by Django 5.0 on 2026-06-18 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', "En attente d'un transporteur"), ('assignee', 'Assignée'), ('en_route', 'En route'), ('arrivee', 'Arrivée à destination'), ('livree', 'Livrée'), ('echec', 'Échec de livraison')], default='en_attente', max_length=20)),
                ('point_depart_lat', models.FloatField(blank=True, null=True)),
                ('point_depart_lng', models.FloatField(blank=True, null=True)),
                ('point_arrivee_lat', models.FloatField(blank=True, null=True)),
                ('point_arrivee_lng', models.FloatField(blank=True, null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('tarif', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('preuve_livraison', models.ImageField(blank=True, null=True, upload_to='preuves/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='commandes.commande')),
                ('transporteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to='accounts.profiltransporteur')),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.vehicule')),
            ],
        ),
    ]
