# Generated by Django 5.0 on 2026-06-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraisons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='derniere_position_maj',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='position_actuelle_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='position_actuelle_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
