# Generated by Django 5.0 on 2026-06-18 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('type_notif', models.CharField(choices=[('commande', 'Commande'), ('paiement', 'Paiement'), ('livraison', 'Livraison'), ('message', 'Message'), ('systeme', 'Système')], max_length=20)),
                ('canal', models.CharField(choices=[('push', 'Push'), ('email', 'Email'), ('sms', 'SMS')], default='push', max_length=10)),
                ('est_lue', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('lien', models.CharField(blank=True, max_length=200)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_envoi'],
            },
        ),
    ]
