# Generated by Django 5.0 on 2026-06-18 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(blank=True, max_length=50)),
                ('categorie_parente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_categories', to='produits.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unite', models.CharField(choices=[('kg', 'Kilogramme'), ('tonne', 'Tonne'), ('sac', 'Sac'), ('litre', 'Litre'), ('piece', 'Pièce'), ('botte', 'Botte'), ('caisse', 'Caisse')], default='kg', max_length=20)),
                ('quantite_disponible', models.FloatField()),
                ('quantite_min_commande', models.FloatField(default=1)),
                ('date_recolte', models.DateField(blank=True, null=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('vendu', 'Épuisé'), ('suspendu', 'Suspendu'), ('en_attente', 'En attente de validation')], default='en_attente', max_length=20)),
                ('est_bio', models.BooleanField(default=False)),
                ('localisation', models.CharField(blank=True, max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('nombre_vues', models.IntegerField(default=0)),
                ('agriculteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='accounts.profilagriculteur')),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='produits.categorie')),
            ],
            options={
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='PhotoProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='produits/')),
                ('est_principale', models.BooleanField(default=False)),
                ('ordre', models.IntegerField(default=0)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='produits.produit')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
